spring.application.name=Zipme


spring.datasource.url=jdbc:postgresql://dpg-d4sp38f5r7bs739ru7dg-a.singapore-postgres.render.com:5432/zipme_db?sslmode=require
spring.datasource.username=zipme_db_user
spring.datasource.password=HsNPcABR8KULnWLqirhItBUBbri4YrKm
spring.datasource.driver-class-name=org.postgresql.Driver


# ---------- H2 database in FILE mode ----------

# spring.datasource.url=jdbc:h2:file:./data/urlsdb;MODE=MySQL;AUTO_RECONNECT=TRUE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---------- Caching ----------

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000,expireAfterAccess=10m

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.cache.interceptor=DEBUG
