spring.application.name=Zipme

# ---------- H2 database in FILE mode ----------

spring.datasource.url=jdbc:h2:file:./data/urlsdb;MODE=MySQL;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---------- Caching ----------

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=10000,expireAfterAccess=10m

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.cache.interceptor=DEBUG
